タスクフォームの追加しました
CODEBASE-Okinawa/1000_hackathon_orin pull request #16
Opened 2022-07-16 13:16 UTC by rin0000

・close #8 
<img width="1349" alt="image" src="https://user-images.githubusercontent.com/105183682/179356474-b9c5f155-8e21-4641-abb3-0d3f6605302d.png">

2022-07-16 14:56 UTC, osatoh requested changes

2022-07-16 14:56 UTC, osatoh commented on app/views/tasks/index.html.erb
> +    <%= f.submit "作成" %>
ここ一行開けたいですね！

```suggestion
  <%= form_with(model: @task, method: :post, local: true) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    
    <%= f.submit "作成" %>
```

2022-07-16 14:56 UTC, osatoh commented on app/controllers/tasks_controller.rb
> +  end
ここ多分`def new` 作らないで、indexの方に `@task = Task.new` 記述したらいけると思います！
```suggestion
  def index
    @task = Task.new
    @tasks_not_yet = Task.where(complete: false)
    @tasks_done = Task.where(complete: true)
  end
```

いけるかの確認も含めてお願いします 🙇

2022-07-16 17:42 UTC, rin0000 commented
#8 
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/105183682/179366198-19cd2f2c-f22c-4108-bed4-3b0726fa79b0.png">

2022-07-16 18:25 UTC, osatoh reviewed
2点確認お願いします 👍

2022-07-16 18:25 UTC, osatoh commented on app/controllers/tasks_controller.rb
> +    @task = Task.new
これで作成できました？ 👀

2022-07-16 18:25 UTC, osatoh commented on app/views/tasks/index.html.erb
> +  <%= form_with(model: @task, method: :post, local: true) do |f| %>
`method: :post` なくても動くか確認お願いします 💪

2022-07-17 00:05 UTC, rin0000 commented on app/controllers/tasks_controller.rb
> +    @task = Task.new
できました！

2022-07-17 00:45 UTC, osatoh reviewed
LGTM!

2022-07-17 00:45 UTC, merged